### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by JacoboRG12** [FurhatRobotics/tutorials#10]
Hi,
is there any way to run the camera feed demo using Python 3.9?
Regards

**Comment by MathieuRH** [comment]
Hey, 
From the Readme :  "Other lower python versions may work, but the requirements don't match 3.9 and higher.", so it won't work with the example in this repository.
You can try using different libraries and tweak the code a bit so that it accepts Python3.9, if you manage to get it to work it would be great for other users ^^
Regards, 
Mathieu
