### ISSUE TITLE
Remote API

### ISSUE THREAD

**Issue by JacoboRG12** [FurhatRobotics/tutorials#12]
Hi again, I have some questions about Python Remote API:

1. I have to develop a program in which the communication language with the robot is in spanish. I'm looking to do it with the Python Remote API but I don't find how to set the input language to spanish.
2. Also I'm trying to set bottoms to use them in the web interface.
3. I don´t find any function to switch between states. Also I don't know if it is possible to define states.
4. Finally, in the Python Remote API example code, you put three furhat.attend() but when a I run the code in the SDK only had efect the last one, so I don't know if there is any way to sync them.

Thanks for your time, but I need to know all this because I have to decide if I do the code in Kotlin or using the Python Remote API.

Regards

**Comment by SquaredCanine** [comment]
Hi there,

1. https://docs.furhat.io/remote-api/ -- the endpoint is furhat/listen
2. Not sure what you mean by 'bottoms'
3. There is no concept of states with the remote-API, if you want to use our more rich API you would need to program in Kotlin/Java.
4. Are there any delays between the attends? And have you tried playing around with the parameters.

I would suggest you use Kotlin, since it will allow you more control of the robot!

Hope this helps!

Regards,
Quinten Stekelenburg

**Comment by JacoboRG12** [comment]
Hi, I wanted to say buttons. Sorry for the mistake and thanks for answering.

**Comment by SquaredCanine** [comment]
Ah, no worries! Buttons are also only available in Kotlin right now :)

**Comment by JacoboRG12** [comment]
Thanks :)
